query SeasonalCatalog($year: Int!, $season: MediaSeason!, $page: Int!, $perPage: Int!, $includeAdultContent: Boolean) {
  Page(page: $page, perPage: $perPage) {
    pageInfo {
      currentPage
      lastPage
      hasNextPage
    }
    media(seasonYear: $year, season: $season, isAdult: $includeAdultContent) {
      id
      type
      format
      status
      title {
        romaji
        english
        native
      }
      synonyms
      episodes
      chapters
      averageScore
      season
      seasonYear
      nextAiringEpisode {
        episode
        airingAt
      }
      siteUrl
      externalLinks {
        site
        url
      }
      streamingEpisodes {
        site
        url
      }
      coverImage {
        medium
        large
        extraLarge
      }
      description
    }
  }
}
