query UserAnimeList($userName: String!, $page: Int, $perPage: Int) {
  MediaListCollection(
    userName: $userName
    type: ANIME
    chunk: $page
    perChunk: $perPage
  ) {
    lists {
      name
      entries {
        mediaId
        status
        score
        progress
        media {
          status
          id
          type
          format
          title {
            romaji
            english
            native
          }
          synonyms
          episodes
          season
          seasonYear
          coverImage { large }
		  description
		  averageScore
		  startDate { year month day }
		  chapters 
		  volumes
		  nextAiringEpisode { airingAt episode }
		  siteUrl
		  streamingEpisodes { site url }
        }
      }
    }
  }
}