query UserAnimeList($userName: String!, $chunk: Int, $perChunk: Int, $status: MediaListStatus) {
  MediaListCollection(
    userName: $userName
    type: ANIME
    status: $status
    chunk: $chunk
    perChunk: $perChunk
  ) {
    hasNextChunk
    lists {
      name
      entries {
        mediaId
        status
        score
        progress
        media {
          status
          id
          type
          format
          title {
            romaji
            english
            native
          }
          synonyms
          episodes
          season
          seasonYear
          coverImage { large }
		  description
		  averageScore
		  startDate { year month day }
		  chapters 
		  volumes
		  nextAiringEpisode { airingAt episode }
		  siteUrl
		  streamingEpisodes { site url }
        }
      }
    }
  }
}
