INSERT INTO media (id, name, english_name, original_name, alternative_names,
                   total_chapters, consumed_chapters, average_score, personal_score, cover_url, cover_medium_url, cover_large_url,
                   cover_extra_large_url, synopsis, type, status, user_list_status, local_path,
                   season, season_year, next_airing_episode, next_airing_at, anilist_url, external_links)
VALUES (:id, :name, :english_name, :original_name, :alternative_names,
        :total_chapters, :consumed_chapters, :average_score, :personal_score, :cover_url, :cover_medium_url, :cover_large_url,
        :cover_extra_large_url, :synopsis, :type, :status, :user_list_status, :local_path,
        :season, :season_year, :next_airing_episode, :next_airing_at, :anilist_url, :external_links)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    english_name = excluded.english_name,
    original_name = excluded.original_name,
    alternative_names = excluded.alternative_names,
    total_chapters = excluded.total_chapters,
    consumed_chapters = excluded.consumed_chapters,
    average_score = excluded.average_score,
    personal_score = excluded.personal_score,
    cover_url = excluded.cover_url,
    cover_medium_url = excluded.cover_medium_url,
    cover_large_url = excluded.cover_large_url,
    cover_extra_large_url = excluded.cover_extra_large_url,
    synopsis = excluded.synopsis,
    type = excluded.type,
    status = excluded.status,
    season = excluded.season,
    season_year = excluded.season_year,
    next_airing_episode = excluded.next_airing_episode,
    next_airing_at = excluded.next_airing_at,
    anilist_url = excluded.anilist_url,
    external_links = excluded.external_links,
    user_list_status = CASE WHEN excluded.user_list_status = -1
                            THEN media.user_list_status ELSE excluded.user_list_status END,
    local_path = CASE WHEN excluded.local_path = '' THEN media.local_path ELSE excluded.local_path END,
    source_removed_at = NULL
